### ISSUE TITLE
Metric Keys missing underscore prefix 

### ISSUE THREAD

**Issue by jamesleaning** [Countly/countly-sdk-cpp#10]
I assume the API has changed at some point. Without the underscore prefix, these metrics are not recognised by the server.

Timestamp information is also missing from the begin/end session requests.

If I was an enterprise customer I would be annoyed with how this SDK doesn't actually work as advertised.

**Comment by LVMBDV** [comment]
This seems to be done correctly in the old version so it seems I broke it during the rewrite :( Should be fixed with df9cbce and 7d7e9cb.
