### ISSUE TITLE
Countly destructor should be virtual

### ISSUE THREAD

**Issue by AndrewAtAvenza** [Countly/countly-sdk-cpp#104]
The `countly` class inherits from `CountlyDelegates`, which has virtual members, which is then overrides. As such, it's destructor should be marked as `virtual`. Building with MSVC with `/permissive-` (now the default) will cause a warning.

**Comment by turtledreams** [comment]
Hello, thank you for reaching out, this has been implemented in the latest release (https://github.com/Countly/countly-sdk-cpp/releases/tag/22.09.1).
