### ISSUE TITLE
Compling Error

### ISSUE THREAD

**Issue by mayenjoy** [Countly/countly-sdk-cpp#11]
2>D:\thirdparty\countly-sdk-cpp\src\countly.cpp(9): fatal error C1083: “openssl/sha.h”: No such file or directory

**Comment by LVMBDV** [comment]
It sounds like you don't have the OpenSSL headers installed. Any chance you forgot to install them or the compiler might not know where to look for them?

**Comment by mayenjoy** [comment]
> It sounds like you don't have the OpenSSL headers installed. Any chance you forgot to install them or the compiler might not know where to look for them?

Yes,  and after I installed libOpenSSL, it works. 

By the way, I use visual studio 2017 and there are also some compiling errors in this project.

but finally I make it compiled. thx your improvements.

**Comment by LVMBDV** [comment]
Cool, I'm glad you got it working without much hassle.
