### ISSUE TITLE
You must specify the correct port in countly::start() or it will not work with WINHTTP

### ISSUE THREAD

**Issue by AndrewAtAvenza** [Countly/countly-sdk-cpp#121]
The API suggests that you can can skip specifying the port and let countly figure it out when you call `start()` but that's not true. If you don't specify it -- or set it to -1 -- it will not work on Windows. The confgiuration `port` member is an `unsigned int` and the value of the `port` parameter gets assigned to it, which results in a huge nonsense value. This causes it to skip over automatic port assignment in `RequestModule::RequestModuleImpl`'s constructor (it checks for <=0, which is a bit silly given it's an `unsigned int`). Specifying 0 is safe, however, as that will trigger the proper responses. The default value for `port` in `start()` should probably be `0` at the very least.

Side note: it's not clear how to start the background thread if you don't do it in the `start()` call. All the code to launch the thread is in `start()`, so I'm guess you can't? Kind of makes that parameter dangerous to leave as the default as well!

**Comment by turtledreams** [comment]
Hi, thank you for bring this up. A fix has been merged and issue would be mitigated at next release (same for the documentation).

**Comment by turtledreams** [comment]
Released https://github.com/Countly/countly-sdk-cpp/releases/tag/23.2.0
