### ISSUE TITLE
UNREFERENCED_PARAMETER is not defined

### ISSUE THREAD

**Issue by Zephilinox** [Countly/countly-sdk-cpp#19]
When building the SDK as described in the readme on windows, I get the following error as the windows header isn't included before this line of code

```
P:\Work\countly-sdk-cpp\include\countly.hpp(145,3): error C3861: 'UNREFERENCED_PARAMETER': identifier not found [P:\Work\countly-sdk-cpp\build\countly.vcxproj]
```

possible solution would be to define the macro if it isn't already defined `#define UNREFERENCED_PARAMETER(P) (P)` (note: the actual implementation in the windows header also handles a special case for the `_PREFAST_` which might be necessary when using MSVC's `/analyze` option 🤷 )

**Comment by turtledreams** [comment]
Hello, thank you for reaching out, UNREFERENCED_PARAMETER(path) including that `#elif` has been removed in the latest release (https://github.com/Countly/countly-sdk-cpp/releases/tag/22.09.1).
