### ISSUE TITLE
Segments use case errors

### ISSUE THREAD

**Issue by mayenjoy** [Countly/countly-sdk-cpp#2]
`		  std::map<string, string> seg;
		  seg["a"] = "a";
		  seg["b"] = "b";
		  seg["c"] = "c";
		  seg["d"] = "d";
		  ct->RecordEvent("test3", seg, 17);
		  break;
`

when I use code like this, the server side say"Could not parse events"

**Comment by osoner** [comment]
thanks for reporting, we'll check and get back to you

**Comment by mayenjoy** [comment]
> thanks for reporting, we'll check and get back to you

Currently, We want migrate from GA to Countly, many thanks to your dedication to make us success.

**Comment by LVMBDV** [comment]
Hi, I've replaced the JSON generation parts with something more standard. Could you check if this fixes your issue @mayenjoy?

**Comment by mayenjoy** [comment]
verified, thanks~
