### ISSUE TITLE
No symbols are exported on windows

### ISSUE THREAD

**Issue by Zephilinox** [Countly/countly-sdk-cpp#21]
There are no macros used to control symbol visibility, and symbols on windows (unlike mac and linux) are hidden by default. Without any exported symbols a `.dll` file is created without the corresponding `.lib`, causing linking to fail.

The cmake target property `WINDOWS_EXPORT_ALL_SYMBOLS` could be used

**Comment by ArtursKadikis** [comment]
Hello, thanks for letting us know. Would it maybe be possible for you to make a PR that would solve the issue for you? Then we would check if it doesn't break anything else.

**Comment by Zephilinox** [comment]
It doesn't particularly block us, as it's easy enough to work around with the cmake flags :) 

`WINDOWS_EXPORT_ALL_SYMBOLS` is a bit of a quick fix compared to using symbol visibility macros, but if you think that's suitable I can submit a one-line PR at some point :b (need to check with my company first about contributing)

**Comment by ArtursKadikis** [comment]
Hello, we've added that flag to the cmake file, and it has been merged into the "staging" branch.
