### ISSUE TITLE
Tests use a C++20 feature despite only requiring C+11

### ISSUE THREAD

**Issue by Zephilinox** [Countly/countly-sdk-cpp#22]
The C++ standard for the tests are specified as C++11, but the tests use C++20 designated initializers

`P:\Work\countly-sdk-cpp\tests\main.cpp(71,35): error C7555: use of designated initializers requires at least '/std:c++20' [P:\Work\countly-sdk-cpp\build\countly-tests.vcxproj]`

either the requirement should be increased to 20 or that C++20 feature was used accidentally and should be removed from the tests

**Comment by ArtursKadikis** [comment]
Thank you for letting us know

**Comment by Zephilinox** [comment]
haha no worries 👍

**Comment by rblenkinsopp** [comment]
I've raised a PR which resolves this here: https://github.com/Countly/countly-sdk-cpp/pull/24

**Comment by ArtursKadikis** [comment]
@Zephilinox which compiler did you use?

**Comment by Zephilinox** [comment]
I think this was with VS 2022, though I'd expect a similar error with VS 2019

**Comment by ArtursKadikis** [comment]
I merged the PR from @rblenkinsopp . The problematic line has been reworked.
