### ISSUE TITLE
Null response when running example on Windows

### ISSUE THREAD

**Issue by Zephilinox** [Countly/countly-sdk-cpp#23]
I've tried it in a VM running Linux which works, and a colleague reports it working on Mac, however I've been unable to get the any data sent when using Windows.

I've tried both static and dynamic linking of the SDK, using the sample in this repository. This is on Windows 10 with the 2019 MSVC compiler.

Events queue up until `[WARNING]Event queue is full, dropping the oldest event to insert a new one` and the session never begins. The response is always `[Debug][Countly][sendHTTP] response: null`. Checking the Count.ly dashboard (we're currently on a trial) shows no new events logged.

Let me know if there is anything you'd like me to do or provide info on to debug this further

**Comment by ArtursKadikis** [comment]
Could you share your SDK init code?

**Comment by Zephilinox** [comment]
It's the sample in this repository https://github.com/Countly/countly-sdk-cpp/blob/21.11.0/examples/example_integration.cpp :)

**Comment by ZahidZafar** [comment]
Hello @Zephilinox,
Could you update the code in the sample app at line 
https://github.com/Countly/countly-sdk-cpp/blob/c6aef59c9b693e5608895d73420215220ad8376a/examples/example_integration.cpp#L40
to `ct.alwaysUsePost(false);` and check if it does work on Windows?

**Comment by Zephilinox** [comment]
sorry, this is high on my list of things to do. hopefully I get to it tomorrow and I can let you know, thanks for the suggestion :)

**Comment by Zephilinox** [comment]
yay that worked :) thanks, setting it to false solves the issue (but I guess it'll still fail on windows if it attempts to send >2kb or whatever the limit is)

**Comment by ArtursKadikis** [comment]
Hello, the fix for this has been merged into the staging branch and will be part of the 21.11.1 release

**Comment by Zephilinox** [comment]
that's awesome news, thanks :)
