### ISSUE TITLE
member variables are uninitialised, leading to segfaults

### ISSUE THREAD

**Issue by Zephilinox** [Countly/countly-sdk-cpp#27]
The member variables for the HTTP client callback and the thread pointer are uninitialized, leading to a segfault when a later check comparing them to nullptr thinks that they are valid.

there might be other issues due to the other variables not being initialised 🤷

**Comment by ArtursKadikis** [comment]
The fix has now been merged into our staging branch and will be release as part of our "21.11.1" release. Let me know if you still have any issues afterwards.
