### ISSUE TITLE
Typo in check in cmakelist for statically-built SDK

### ISSUE THREAD

**Issue by Zephilinox** [Countly/countly-sdk-cpp#31]
`if (NOT WIN32 AND NOT BUILD_SHARED_LIBS AND NOT COUNTLY_CUSTOM_HTTP)`

`COUNTLY_CUSTOM_HTTP` should be `COUNTLY_USE_CUSTOM_HTTP`

this causes cmake to fail to configure

**Comment by ArtursKadikis** [comment]
Thanks for letting us know about this. The fix for this will be included in the next release.

**Comment by ArtursKadikis** [comment]
Hello, the fix for this has been merged into the staging branch and will be part of the 21.11.1 release
