### ISSUE TITLE
SDK fails to compile when using COUNTLY_USE_CUSTOM_HTTP

### ISSUE THREAD

**Issue by Zephilinox** [Countly/countly-sdk-cpp#32]
https://github.com/Countly/countly-sdk-cpp/blob/master/src/countly.cpp#L665

`return false` in `sendHTTP` isn't valid, as it needs to return an HTTPResponse

**Comment by ArtursKadikis** [comment]
The fix has now been merged into our staging branch and will be release as part of our "21.11.1" release.
