### ISSUE TITLE
Cannot send events without using POST on linux

### ISSUE THREAD

**Issue by Loic-Corenthy** [Countly/countly-sdk-cpp#37]
While testing the cpp SDK, in an linux container on Docker (Ubuntu 20.04), I had to always use post to be able to send events to Countly 
For example:
`countly.alwaysUsePost(true);`

In other words, it seemed impossible to send events using GET instead of POST.

Corresponding Error message: `[Debug][Countly][sendHTTP] response: null`

**Comment by ArtursKadikis** [comment]
This issue should be fixed in the "21.11.1" release. Let us know if it still persists.
