### ISSUE TITLE
Too many sql execute count when report event to server

### ISSUE THREAD

**Issue by bhui** [Countly/countly-sdk-cpp#5]
```
for (int i = 0; i < _maxEvents; i++) {
    json = queue->PopEvent(&evtId, i);
    if (evtId == -1) break;
    evtIds.push_back(evtId);
    if (i > 0) all = all + ",";
    all = all + json;
}
```

```
string CountlyEventQueue::PopEvent(int* evtId, size_t offset) {
...
  snprintf(req, "SELECT evtid, event FROM events LIMIT 1 OFFSET %d", offset);
...
```

**Comment by LVMBDV** [comment]
Given that `CountlyEventQueue::PopEvent`'s only use is iterative, executing that SQL query N times consecutively instead of once seems kind of wasteful. I'll experiment with a new method that will do it in one query. In the meantime, can you provide some profiling results that made you notice this?

**Comment by LVMBDV** [comment]
The rewrite fixes this by fetching multiple events at once when updating session data, closing this.
