### ISSUE TITLE
Wrong checksum resulting in "Request does not match checksum" response

### ISSUE THREAD

**Issue by Loic-Corenthy** [Countly/countly-sdk-cpp#50]
When using salt, the checksum in `sendHTTP` is not constructed correctly resulting in the server not being able to validate the message and returning error 200: "Request does not match checksum"

Example of non valid checksum:
"checksum256": " O â  Ã° k Ã³ \n Ë ~ Ãº Ë Ã® ' Â¨ P w  Âª 9 Â° \u0013 \u0014 a â Ã£ ! ) F Â´ g 6 , Â¾"

Our fix was to replace:
`checksum_stream << std::setw(2) << std::hex << checksum[index];` (line 824)

with the following:
`checksum_stream << std::setfill('0') << std::setw(2) << std::hex << static_cast<int>(checksum[index]);`

**Comment by ZahidZafar** [comment]
This is issue has been fixed in the latest release (21.11.2). 
Thank you @Loic-Corenthy for letting us know.
