### ISSUE TITLE
Use delete [] instead of just delete for arrays

### ISSUE THREAD

**Issue by Loic-Corenthy** [Countly/countly-sdk-cpp#53]
In the `sendHTTP` method, the `wide_path` and `body_part` arrays should be deleted using the [] syntax:
`delete [] wide_path;` (line 886) 
`delete [] body_part;` (line 920 and line 925)

**Comment by ArtursKadikis** [comment]
Hello, this is fixed now and will be released in the version marked as "21.11.3" later this week.
Thank you for letting us know about this.
