### ISSUE TITLE
Initialize internet handles

### ISSUE THREAD

**Issue by Loic-Corenthy** [Countly/countly-sdk-cpp#54]
In the `sendHTTP` method, we had a crash in our tests when building in debug mode (only in debug, not in release) with a message along the lines of "`hRequest` used without being initialized".
Our simple fix was to initialize the handles to nullptr:
`HINTERNET hSession = nullptr;` (line 859)
`HINTERNET hConnect = nullptr;` (line 860)
`HINTERNET hRequest = nullptr;` (line 861)

**Comment by ArtursKadikis** [comment]
Hello, this is fixed now and will be released in the version marked as "21.11.3" later this week.
Thank you for letting us know about this.
