### ISSUE TITLE
No exception handling during JSON parsing.

### ISSUE THREAD

**Issue by jamesleaning** [Countly/countly-sdk-cpp#65]
In the event that the recieved JSON text is not valid, it may cause a crash.

A check such as the following should be undertaken:

						const auto& parseResult = json::parse(body, nullptr, false);
						if(!parseResult.is_discarded())
						{
							response.data = parseResult;
						}

-----------------

Last week an automated nightly Server OS update disrupted the functionality of my Countly server.
This left the country server in an active but unresponsive state (simply restarting the server fix this).

Anyway, this caused my customers to have major issues opening my App. Lots of very angry people!

**Comment by ArtursKadikis** [comment]
Hello, this is fixed now and will be released in the version marked as "21.11.4" in a few days.
Thank you for letting us know about this.
