### ISSUE TITLE
Excessive HTTP timeout required

### ISSUE THREAD

**Issue by jamesleaning** [Countly/countly-sdk-cpp#66]
When a Countly server is not responsive, the Windows default timeout values can cause a App to lock for a 'long' time.

A change such as the following should be made:

		// Set way Shorter timeouts:
		WinHttpSetTimeouts(hSession,
						   10000,	// nResolveTimeout: 10sec (default 'infinite').
						   10000,	// nConnectTimeout: 10sec (default 60sec).
						   10000,	// nSendTimeout: 10sec (default 30sec).
						   10000);	// nReceiveTimeout: 10sec (default 30sec).

-----------------

Last week an automated nightly Server OS update disrupted the functionality of my Countly server.
This left the country server in an active but unresponsive state (simply restarting the server fix this).

Anyway, this caused my customers to have major issues opening my App. Lots of very angry people!

**Comment by ArtursKadikis** [comment]
Hello, we applied these timeout values in the release we just had (22.02.0).
Thank you for letting us know about this issue.
