### ISSUE TITLE
Chinese Char can't be used in segmentation.

### ISSUE THREAD

**Issue by mayenjoy** [Countly/countly-sdk-cpp#7]
std::map<string, string> seg;
		  seg["a"] = "a";
		  seg["b"] = "b";
		  seg["c"] = "c";
		  seg["d"] = u8测试联移动测试符号";
		  ct->RecordEvent("test3", seg, 1);

with exception blow:

CountlyCppTestStatic.exe!_chvalidator(c=-23, mask=263) 行 36
CountlyCppTestStatic.exe!fast_check(c=-23, mask=263) 行 20
CountlyCppTestStatic.exe!isalnum(c=-23) 行 151
CountlyCppTestStatic.exe!CountlyCpp::CountlyConnectionQueue::URLEncode(value={...}) 行 217

**Comment by mayenjoy** [comment]
ps: I use vs 2017 under windows 10.

**Comment by LVMBDV** [comment]
Hi, encoding is a finicky subject since the C++ stdlib doesn't really define a certain encoding in its string definition. Most *nix tools use UTF-8 so it's a good default to fall back to. We've recently reimplemented the SDK while preserving the old API, could you check if the problem persists?
