### ISSUE TITLE
Http Get String Length is too short 

### ISSUE THREAD

**Issue by mayenjoy** [Countly/countly-sdk-cpp#8]
`bool CountlyEventQueue::RecordEvent(string key,
    std::map<string, string> segmentation, int count) {
  ArduinoJson::StaticJsonBuffer<512> jsonBuffer;
`

If the segement param is a long string, the app will crash.

**Comment by LVMBDV** [comment]
Hi, We've recently reimplemented the SDK, the new JSON library we use mostly uses dynamic allocation, could you check if the problem persists?
